In [15]:
!ls jobs


job_05_20_14_23_30         job_05_25_10_45_46_log.txt
job_05_20_14_45_37         job_05_25_12_42_29
job_05_20_14_59_59         job_05_25_12_56_28
job_05_20_15_00_56         job_05_25_13_41_46
job_05_20_15_10_10         job_05_25_15_14_21
job_05_20_15_10_41         job_05_26_08_40_43
job_05_20_15_11_26         job_05_26_08_55_31
job_05_20_15_17_45         job_05_26_08_57_11
job_05_20_17_16_03         job_05_26_14_50_07
job_05_22_08_54_05         job_05_26_15_04_25
job_05_22_12_25_34         job_05_27_11_52_53
job_05_22_17_41_48         job_05_27_13_10_13
job_05_22_19_12_28         job_05_28_07_50_10
job_05_23_04_22_42         job_05_28_07_50_13
job_05_23_10_16_58         job_05_28_07_50_27
job_05_23_10_31_52         job_05_28_09_32_39
job_05_23_10_56_58         job_05_28_11_39_48
job_05_23_11_59_46         job_05_28_11_50_43
job_05_23_12_41_26         job_05_28_13_53_37
job_05_23_17_15_25         job_05_28_15_42_46
job_05_23_17_37_25         job_05_28_15_56_40
job_05_24_08_57_04        

In [27]:
import pandas as pd
import os
import numpy as np

In [115]:
job_list = ["job_05_28_19_47_35",
            "job_05_28_18_45_33",
            "job_05_28_15_56_40",
            "job_05_28_11_39_48",
            "job_05_28_09_32_39"
           ]



In [124]:
job_list = ["job_05_28_19_47_35",
            "job_05_28_18_45_33",
            "job_05_28_15_56_40",
            "job_05_28_11_39_48",
            "job_05_28_09_32_39",
            "job_05_28_11_50_43"
           ]

In [78]:
sum_pred = pd.read_csv(os.path.join(*["jobs","job_05_28_19_47_35","y_test.txt"]),header=None)
y_pred_1 = pd.read_csv(os.path.join(*["jobs","job_05_28_19_47_35","y_test.txt"]),header=None)

print(np.sum(sum_pred[0].values))

for i in range(1,len(job_list)):
    pred_job = pd.read_csv(os.path.join(*["jobs",job_list[i],"y_test.txt"]),header=None)
    print(np.sum(pred_job[0].values))
    sum_pred = sum_pred+pred_job
    
y_pred = sum_pred[0].values
print(y_pred)

y_pred = (y_pred/5)*2-1.0
y_pred = np.sign(y_pred)
y_pred = np.maximum(y_pred,0.0)

print(y_pred)

result_str = ""
for i in range(len(y_pred)):
    result_str+=str(int(y_pred[i]))
    result_str+="\n"

result_file = open("y_test_2.txt","w")
result_file.write(result_str)
result_file.close()

29624
31293
29812
30090


In [116]:
sum_dist = np.load(os.path.join(*["jobs","job_05_28_18_45_33","d_test_ep9.npy"]))
y_pred = dist[:,1]-dist[:,0]
dist = np.load(os.path.join(*["jobs","job_05_28_13_53_37","d_test_epoch8.npy"]))
y_pred = dist[:,1]-dist[:,0]
sum_dist = sum_dist+dist

for i in range(0,len(job_list)):
    dist = np.load(os.path.join(*["jobs",job_list[i],"d_test.npy"]))
    y_pred = dist[:,1]-dist[:,0]
    sum_dist = sum_dist + dist

dist = dist/8


In [125]:
def d_2_y(dist):
    y_pred = dist[:,1]-dist[:,0]
    y_pred = np.sign(y_pred)
    y_pred = np.maximum(y_pred,0.0)
    return y_pred

In [130]:
dist = np.load(os.path.join(*["jobs","job_05_28_18_45_33","d_test_ep9.npy"]))
sum_y_pred = d_2_y(dist)
#dist = np.load(os.path.join(*["jobs","job_05_28_13_53_37","d_test_epoch8.npy"]))
#y_pred = d_2_y(dist)
#sum_y_pred += y_pred

for i in range(0,len(job_list)):
    dist = np.load(os.path.join(*["jobs",job_list[i],"d_test.npy"]))
    y_pred = d_2_y(dist)
    sum_y_pred += y_pred

sum_y_pred = sum_y_pred/7



In [132]:
sum_y_pred = sum_y_pred*2-1.0

In [134]:
y_pred = np.sign(sum_y_pred)
y_pred = np.maximum(y_pred,0.0)

In [133]:
sum_y_pred

array([ 0.42857143, -1.        , -0.71428571, ...,  0.14285714,
        1.        , -0.42857143])

In [136]:
np.sum(y_pred)

30364.0

In [137]:
result_str = ""
for i in range(len(y_pred)):
    result_str+=str(int(y_pred[i]))
    result_str+="\n"

result_file = open("y_test_5.txt","w")
result_file.write(result_str)
result_file.close()

In [119]:
y_pred = np.sign(y_pred)
y_pred = np.maximum(y_pred,0.0)

In [120]:
print(np.sum(y_pred))

30090.0


In [122]:


print(y_pred)

result_str = ""
for i in range(len(y_pred)):
    result_str+=str(int(y_pred[i]))
    result_str+="\n"

result_file = open("y_test_4.txt","w")
result_file.write(result_str)
result_file.close()

[0. 0. 1. ... 0. 1. 0.]


[3 0 1 ... 3 5 1]


[1. 0. 0. ... 1. 1. 0.]


In [92]:
b = (y_pred_1.values).flatten()

In [93]:
c = y_pred*b

In [94]:
np.sum(c)

26412.0

In [96]:
!ls

Untitled.ipynb          iml4_colab_2305_2.ipynb task4_models.py
__pycache__             iml4_colab_2605.ipynb   task4_utils.py
combine_preds.py        jobs                    task4_utils.py.bk
custom_objects.py       preprocessor.py         task4_utils.py.bk2
custom_objects_2.py     snippets.py             y_test_2.txt
data                    task4_2005.ipynb
iml4_colab_2005.ipynb   task4_2005.py
