In [ ]:
# ONLY RUN ONCE TO SETUP THE ENVIRONMENT
from getpass import getpass
import urllib
import os
from random import sample
from glob import glob

# cleanup previouiml runs
!rm -r iml-hs21

# load data from github repo
user = input('User name: ')
password = getpass('Password: ')
password = urllib.parse.quote(password) # your password is converted into url format
repo_name = 'iml-hs21'
cmd_string = 'git clone https://{0}:{1}@github.com/{2}/{3}.git'.format(user, password, 'hanyao8', repo_name)
os.system(cmd_string)
cmd_string, password = "", "" # removing the password from the variable




rm: cannot remove 'iml-hs21': No such file or directory
User name: hanyao8
Password: ··········


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/iml-hs21/task4
!ls

import IPython.display as display
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import os

#from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.optimizers import Adam

from tensorflow import keras
from tensorflow.keras import layers

from tensorflow.keras import metrics
from tensorflow.keras import losses
from tensorflow.keras import optimizers

from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array

from keras.models import Model

#from keras.applications.mobilenet import preprocess_input
from keras.applications import mobilenet
from keras.applications import MobileNetV2
from keras.applications import VGG16

import pandas as pd
from datetime import datetime

from sklearn.model_selection import train_test_split

from task4_utils import *
#from task4_models import *

print(tf.__version__)
print(keras.__version__)


/content/iml-hs21/task4
custom_objects.py  jobs		     task4_2005.py    task4_utils.py
data		   task4_2005.ipynb  task4_models.py
2.4.1
2.4.0


In [ ]:
!git pull

Already up to date.


In [ ]:
#setup logging
#setup new job directory
CWD = os.getcwd()
print(CWD)

now = datetime.now()
job_time = now.strftime("%m_%d_%H_%M_%S")
print("Job Start Time =", job_time)

if not(os.path.exists("jobs")):
    os.mkdir("jobs")
CURRENT_JOB_PATH = os.path.join(*[CWD,"jobs","job_"+job_time])
os.mkdir(CURRENT_JOB_PATH)
JOB_LOG = open(os.path.join(CURRENT_JOB_PATH,"log.txt"),"a")
JOB_LOG.write("init\n")

print("\nCurrent Job Path: %s \n"%CURRENT_JOB_PATH)

os. environ['SM_FRAMEWORK'] = 'tf.keras'

# automatically chooses parameters
AUTOTUNE = tf.data.experimental.AUTOTUNE
print(f"Tensorflow ver. {tf.__version__}")
gpus = tf.config.experimental.list_physical_devices('GPU')
tpus = tf.config.experimental.list_physical_devices('TPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        print(e)
#elif tpus:
#    print("TPU")



/content/iml-hs21/task4
Job Start Time = 05_23_04_22_42

Current Job Path: /content/iml-hs21/task4/jobs/job_05_23_04_22_42 

Tensorflow ver. 2.4.1
1 Physical GPUs, 1 Logical GPUs


In [ ]:
HOLD_FRAC = 0.5
TRAIN_DATASET_SIZE = "default"

### Get data
sample = pd.read_table("data/sample.txt",header=None)
train_hold_triplets = pd.read_table("data/train_triplets.txt",delimiter=" ",header=None,dtype=str)
train_triplets, pos_hold_triplets = train_test_split(train_hold_triplets,test_size=HOLD_FRAC)
test_triplets = pd.read_table("data/test_triplets.txt",delimiter=" ",header=None,dtype=str)

if TRAIN_DATASET_SIZE == "default":
    train_dataset_size = train_triplets.shape[0]
else:
    train_dataset_size = TRAIN_DATASET_SIZE

now = datetime.now()
this_time = now.strftime("%m_%d_%H_%M_%S")
print("This Time =", this_time)

train_dataset, val_dataset = train_val_dataset_from_df(train_triplets,train_dataset_size)

hold_triplets = hold_triplets_from_pos(pos_hold_triplets)
hold_dataset = hold_dataset_from_df(hold_triplets)
y_hold_groundtruth = hold_gt_from_df(hold_triplets)

test_dataset = test_dataset_from_df(test_triplets)

now = datetime.now()
this_time = now.strftime("%m_%d_%H_%M_%S")
print("This Time =", this_time)
print("\nCurrent Job Path: %s \n"%CURRENT_JOB_PATH)

This Time = 05_23_04_22_52
29757
59516
59544
This Time = 05_23_04_23_44

Current Job Path: /content/iml-hs21/task4/jobs/job_05_23_04_22_42 



In [7]:
import custom_objects

###Siamese Network approach

def create_siamese():
    feature_cnn = MobileNetV2(weights="imagenet",
                              input_shape=(224,224,3),
                              include_top=False)

    for layer in feature_cnn.layers:
        layer.trainable = True

    flatten = layers.Flatten()(feature_cnn.output)
    dense = layers.Dense(512,activation="relu")(flatten)
    dense = layers.BatchNormalization()(dense)
    output = layers.Dense(256)(dense)
    embedding = Model(feature_cnn.input,output,name="Embedding")

    anchor_input = layers.Input(name="anchor", shape=(224,224,3))
    positive_input = layers.Input(name="positive", shape=(224,224,3))
    negative_input = layers.Input(name="negative", shape=(224,224,3))

    distances = custom_objects.DistanceLayer()(
        embedding(mobilenet.preprocess_input(anchor_input)),
        embedding(mobilenet.preprocess_input(positive_input)),
        embedding(mobilenet.preprocess_input(negative_input)),
    )

    siamese_network = Model(
    inputs=[anchor_input, positive_input, negative_input], outputs=distances
    )

    return (siamese_network)

In [9]:
#Experiment = job_05_23_03_37_02, n_train=29k

now = datetime.now()
this_time = now.strftime("%m_%d_%H_%M_%S")
print("This Time =", this_time)
print("\nCurrent Job Path: %s \n"%CURRENT_JOB_PATH)

#siamese_model = SiameseModel(siamese_network)
siamese_network = create_siamese()
siamese_model = custom_objects.SiameseModel(siamese_network)

callbacks = [keras.callbacks.ModelCheckpoint(
        os.path.join(CURRENT_JOB_PATH,"save_at_{epoch}.h5")),]

siamese_model.compile(optimizer=optimizers.Adam(1.0e-6))

siamese_model.fit(train_dataset, epochs=10, callbacks=callbacks, validation_data=val_dataset)
#siamese_model.fit(train_dataset, epochs=10, validation_data=val_dataset)

now = datetime.now()
this_time = now.strftime("%m_%d_%H_%M_%S")
print("This Time =", this_time)


This Time = 05_23_04_24_39

Current Job Path: /content/iml-hs21/task4/jobs/job_05_23_04_22_42 

9412608/9406464 [==============================] - 0s 0us/step
Epoch 1/10
744/744 [==============================] - 623s 802ms/step - loss: 0.5024 - val_loss: 0.4738
Epoch 2/10
744/744 [==============================] - 596s 801ms/step - loss: 0.4653 - val_loss: 0.4626
Epoch 3/10
744/744 [==============================] - 594s 799ms/step - loss: 0.4561 - val_loss: 0.4583
Epoch 4/10
744/744 [==============================] - 595s 799ms/step - loss: 0.4499 - val_loss: 0.4580
Epoch 5/10
744/744 [==============================] - 592s 796ms/step - loss: 0.4420 - val_loss: 0.4541
Epoch 6/10
744/744 [==============================] - 592s 796ms/step - loss: 0.4353 - val_loss: 0.4551
Epoch 7/10
744/744 [==============================] - 592s 796ms/step - loss: 0.4286 - val_loss: 0.4447
Epoch 8/10
744/744 [==============================] - 586s 788ms/step - loss: 0.4228 - val_loss: 0.4411
Epoch 9/1

In [ ]:
#Save "final model dir"

iterator = iter(test_dataset)

sample = iterator.get_next()
pred = siamese_model.predict_on_batch(sample)

In [ ]:
pred

(array([1.0384614 , 1.1825669 , 1.0420566 , 0.58512706, 1.2902412 ,
        0.9404453 , 1.1131577 , 1.5248908 , 1.0946522 , 1.3167863 ,
        1.2790881 , 1.1058254 , 0.7615142 , 2.2250843 , 0.8899875 ,
        0.97397274, 1.0738329 , 1.2598209 , 0.70994675, 1.0576506 ,
        1.8398006 , 1.7653145 , 1.0877423 , 1.2538393 , 1.9744084 ,
        0.9818154 , 2.170514  , 1.6499933 , 1.074878  , 1.1435493 ,
        1.1553273 , 1.2246672 ], dtype=float32),
 array([1.4269474 , 1.0568583 , 0.636912  , 0.55563927, 1.2737523 ,
        1.2813208 , 1.9624313 , 1.3491409 , 2.011571  , 1.4351068 ,
        1.8994048 , 0.7496568 , 0.67338   , 0.93510395, 1.0353622 ,
        1.204777  , 1.521352  , 1.2191112 , 0.8172906 , 0.6953639 ,
        1.1695046 , 1.2225847 , 2.3839424 , 0.705729  , 1.4576864 ,
        1.0332758 , 1.546669  , 1.090463  , 1.6873591 , 1.3233571 ,
        1.138345  , 1.3687804 ], dtype=float32))

In [ ]:
siamese_model.save(os.path.join(CURRENT_JOB_PATH,"final_model"))

INFO:tensorflow:Assets written to: /content/iml-hs21/task4/jobs/job_05_22_19_12_28/final_model/assets


In [ ]:
!zip -r /content/iml-hs21/task4/latest_jobs_dir.zip  /content/iml-hs21/task4/jobs

updating: content/iml-hs21/task4/jobs/ (stored 0%)
updating: content/iml-hs21/task4/jobs/job_05_22_12_25_34/ (stored 0%)
updating: content/iml-hs21/task4/jobs/job_05_22_12_25_34/d_test.npy (deflated 49%)
updating: content/iml-hs21/task4/jobs/job_05_22_12_25_34/log.txt (stored 0%)
updating: content/iml-hs21/task4/jobs/job_05_22_12_25_34/y_test.txt (deflated 91%)
updating: content/iml-hs21/task4/jobs/job_05_20_15_00_56/ (stored 0%)
updating: content/iml-hs21/task4/jobs/job_05_20_15_00_56/log.txt (stored 0%)
updating: content/iml-hs21/task4/jobs/job_05_20_15_00_56/sub.txt (deflated 90%)
updating: content/iml-hs21/task4/jobs/job_05_20_14_59_59/ (stored 0%)
updating: content/iml-hs21/task4/jobs/job_05_20_14_59_59/log.txt (stored 0%)
updating: content/iml-hs21/task4/jobs/job_05_22_17_41_43/ (stored 0%)
updating: content/iml-hs21/task4/jobs/job_05_22_17_41_43/log.txt (stored 0%)
updating: content/iml-hs21/task4/jobs/job_05_20_17_16_03/ (stored 0%)
updating: content/iml-hs21/task4/jobs/job_05_

In [ ]:
!ls ../../drive/MyDrive

'15_Altwiesestr._EG re_Han Yao_signed.pdf'
 449877969-Karen-Morrison.pdf
'Active Notes.gdoc'
 altwiesen2_docs
 Archive
 best_photos
 blinded_by_light.pdf
 Career
'Career Planning Document.gdoc'
'Colab Notebooks'
 colab_projects
'Copy of GreenWeb Ideas.gdoc'
'Copy of IGCSE 数学和物理提高班.gdoc'
'Copy of Kosmos top10 history.gdoc'
'Copy of photo_2021-04-12_23-01-47.jpg'
 econ1.pdf
 eth
 File_000.jpeg
'GreenWeb Ideas.gdoc'
 homagecatalonia-2.pdf
 HYChoong_CV_11_03_2021.gdoc
 icl
'IGCSE 数学和物理提高班.gdoc'
 IMG_5086.JPG
 IMG_5611.JPG
 IMG_6243.PNG
 IMG_6244.PNG
 latest_jobs_dir_2205_1414.zip
 latest_jobs_dir.zip
 library
 log_20201228.gdoc
 logs_notes
 ODS_FS21_LN_combined.pdf
 papers
'Personal Information Documents'
 photo_2021-04-12_23-01-47.jpg
 print
'Project A'
'Project Shortlist.gdoc'
 Robot_Dynamics_Lecture_Notes.pdf
'Screenshot from 2020-12-03 09-20-02.png'
'self learning'
 sheltering_sky.pdf
'swiss trip 2018 photos'
 Textbook_LNs
 Textbooks
 tutoring
'Untitled document (1).gdoc'
'Untitled doc

In [ ]:
!rm /content/drive/MyDrive/latest_jobs_dir.zip
!cp /content/iml-hs21/task4/latest_jobs_dir.zip   /content/drive/MyDrive/latest_jobs_dir.zip

In [ ]:
#load model

saved_model_path = os.path.join(CURRENT_JOB_PATH,"final_model")
#saved_model_path = os.path.join(CURRENT_JOB_PATH,"save_at_2.h5")
siamese_model_2 = keras.models.load_model(saved_model_path)

In [ ]:
siamese_model_2.load_weights(os.path.join(CURRENT_JOB_PATH,"save_at_5.h5"))

In [ ]:
pred2 = siamese_model_2.predict_on_batch(sample)

In [ ]:
pred2

(array([0.22566554, 0.3220632 , 0.30989063, 0.50195   , 0.31910244,
        0.26597843, 0.31678402, 0.34881294, 0.33191234, 0.33603102,
        1.2478342 , 0.5456886 , 0.5998326 , 0.55203265, 0.3533888 ,
        0.8567978 , 0.13334706, 0.37616915, 0.4347327 , 0.244641  ,
        0.8463795 , 0.812516  , 1.0245826 , 0.63009936], dtype=float32),
 array([0.37783486, 0.7142782 , 0.47728133, 0.5410254 , 0.46441248,
        0.44499913, 0.6944829 , 0.18182188, 0.4160807 , 0.85261095,
        0.87592757, 0.45011383, 0.26053023, 0.6969905 , 0.5910849 ,
        0.32948226, 0.59055907, 0.43063474, 0.1980359 , 0.9294046 ,
        0.51239306, 0.4139275 , 0.28971565, 0.5718756 ], dtype=float32))

In [10]:
#hold pred
hold_dataset_size = hold_triplets.shape[0]
batch_size = 32
batches_to_pred = int(hold_dataset_size/batch_size + 1)
d_hold = np.zeros( ( hold_dataset_size,2 ) )

print(batches_to_pred)

now = datetime.now()
this_time = now.strftime("%m_%d_%H_%M_%S")
print("This Time =", this_time)

iterator = iter(hold_dataset)
for i in range(batches_to_pred-1):
    sample = iterator.get_next()
    pred = siamese_model.predict_on_batch(sample)
    d_hold[i*batch_size:(i+1)*batch_size,0] = pred[0]
    d_hold[i*batch_size:(i+1)*batch_size,1] = pred[1]
    if i%50==0:
        print(i)

now = datetime.now()
this_time = now.strftime("%m_%d_%H_%M_%S")
print("This Time =", this_time)

print("\n\n\n")

if hold_dataset_size > (batches_to_pred-1)*batch_size:
    #last batch (size=24)
    sample = iterator.get_next()
    pred = siamese_model.predict_on_batch(sample)

    final_start = (batches_to_pred-1)*batch_size
    final_batch_size = sample[0].shape[0]

    d_hold[final_start:final_start+final_batch_size,0] = pred[0]
    d_hold[final_start:final_start+final_batch_size,1] = pred[1]


1860
This Time = 05_23_06_03_51
0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400
1450
1500
1550
1600
1650
1700
1750
1800
1850
This Time = 05_23_06_12_45






In [11]:
d_hold_save_path = os.path.join(CURRENT_JOB_PATH,"d_hold.npy")
with open(d_hold_save_path,'wb') as f:
    np.save(f,d_hold)


In [ ]:
y_hold_pred = np.sign(d_hold[:,1]-d_hold[:,0])
y_hold_pred = (y_hold_pred+1)/2
y_hold_pred = y_hold_pred.astype(int)

In [23]:
from sklearn.metrics import accuracy_score, recall_score, precision_score

#job_05_22_19_12_28

acc = accuracy_score(y_hold_groundtruth,y_hold_pred)
print(acc)

rec = recall_score(y_hold_groundtruth,y_hold_pred)
print(rec)

prec = precision_score(y_hold_groundtruth,y_hold_pred)
print(prec)

now = datetime.now()
this_time = now.strftime("%m_%d_%H_%M_%S")
print("This Time =", this_time)

0.5940923449156529
0.5940923449156529
0.5940923449156529
This Time = 05_23_06_31_32


In [13]:
#test pred

test_dataset_size = test_triplets.shape[0]
batch_size = 32
batches_to_pred = int(test_dataset_size/batch_size + 1)
#d_test = np.zeros( ( batches_to_pred*batch_size,2 ) )
d_test = np.zeros( ( test_dataset_size,2 ) )

print(batches_to_pred)

iterator = iter(test_dataset)
for i in range(batches_to_pred-1):
    sample = iterator.get_next()
    pred = siamese_model.predict_on_batch(sample)
    d_test[i*batch_size:(i+1)*batch_size,0] = pred[0]
    d_test[i*batch_size:(i+1)*batch_size,1] = pred[1]
    if i%20==0:
        print(i)

print("\n\n\n")

if test_dataset_size > (batches_to_pred-1)*batch_size:
    #last batch (size=24)
    sample = iterator.get_next()
    pred = siamese_model.predict_on_batch(sample)

    print(d_test)
    print(d_test[-40:])
    final_start = (batches_to_pred-1)*batch_size
    final_batch_size = sample[0].shape[0]
    print(final_batch_size)
    d_test[final_start:final_start+final_batch_size,0] = pred[0]
    d_test[final_start:final_start+final_batch_size,1] = pred[1]
    print(d_test)
    print(d_test[-40:])

1861
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
1720
1740
1760
1780
1800
1820
1840




[[0.57399511 0.78214109]
 [0.59976447 0.65765995]
 [0.88422656 0.56407732]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.87869692 0.92599505]
 [0.97439259 1.35976481]
 [0.3539041  0.59543395]
 [0.83154023 1.11359453]
 [0.60276973 0.48554856]
 [0.86325943 0.41913149]
 [1.48368192 1.70479393]
 [0.87709796 1.15289104]
 [1.17587292 0.64760113]
 [1.18046927 0.93908107]
 [0.75123948 2.24162769]
 [0.56171548 0.40481043]
 [1.15422511 1.143152  ]
 [0.61925983 0.62392122]
 [1.04747081 1.1078676 ]
 [1.57422304 0.70609641]
 [0.         0.        ]
 

In [14]:
d_test_save_path = os.path.join(CURRENT_JOB_PATH,"d_test.npy")
with open(d_test_save_path,'wb') as f:
    np.save(f,d_test)
y_test = np.sign(d_test[:,1]-d_test[:,0])
y_test = (y_test+1)/2
y_test = y_test.astype(int)

In [ ]:
y_test[:100]

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1])

In [15]:
result_str = ""
for i in range(len(y_test)):
    result_str+=str(int(y_test[i]))
    result_str+="\n"

result_file = open(os.path.join(CURRENT_JOB_PATH,"y_test.txt"),"w")
result_file.write(result_str)
result_file.close()

In [16]:
JOB_LOG.close()

In [17]:
!ls
!ls jobs

custom_objects.py  jobs		task4_2005.ipynb  task4_models.py
data		   __pycache__	task4_2005.py	  task4_utils.py
job_05_20_14_59_59  job_05_20_15_11_26	job_05_22_12_25_34  job_14:37:30
job_05_20_15_00_56  job_05_20_15_17_45	job_05_22_17_41_48
job_05_20_15_10_10  job_05_20_17_16_03	job_05_22_19_12_28
job_05_20_15_10_41  job_05_22_08_54_05	job_05_23_04_22_42


In [18]:
!git config --global user.email "choong.hanyao@gmail.com"
!git config --global user.name "hanyao8"

In [19]:
!git pull

Already up to date.


In [ ]:
cmd_string = 'git clone https://{0}:{1}@github.com/{2}/{3}.git'.format(user, password, 'hanyao8', repo_name)
os.system(cmd_string)

In [20]:
#job_05_22_19_12_28
!git add jobs/job_05_23_04_22_42/d_test.npy
!git add jobs/job_05_23_04_22_42/log.txt
!git add jobs/job_05_23_04_22_42/y_test.txt

In [21]:
!git commit -m "add colab jobs job_05_23_04_22_42"

[main 159bb40] add colab jobs job_05_23_04_22_42
 3 files changed, 59545 insertions(+)
 create mode 100644 task4/jobs/job_05_23_04_22_42/d_test.npy
 create mode 100644 task4/jobs/job_05_23_04_22_42/log.txt
 create mode 100644 task4/jobs/job_05_23_04_22_42/y_test.txt


In [ ]:
cmd_string = "git add %s"%(CURRENT_JOB_DIR)

In [22]:
!git push origin main

Counting objects: 7, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 474.47 KiB | 3.54 MiB/s, done.
Total 7 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/hanyao8/iml-hs21.git
   3991de9..159bb40  main -> main


In [ ]:
#os.path.getsize("save_at_1.h5")
test_dataset
#sample = next(iter(test_dataset))
iterator = iter(test_dataset)
sample = iterator.get_next()
pred = siamese_model.predict(sample)
pred[0].shape
d_test[0:32,0] = np.arange(0,32)
d_test[0:40]
int(test_dataset_size/batch_size)

sample_rgb = (sample[0]*256,
          sample[1]*256,
          sample[2]*256)

sample_rgb

plt.imshow(np.asarray(sample_rgb[0],dtype=int))
#visualize(np.array(sample[0]) ,sample[1],sample[2])
#visualize(*list(train_dataset.take(1).as_numpy_iterator())[0])

iterator_train = iter(train_dataset)
sample_train = iterator_train.get_next()
print(sample_train[0].shape)
pred = siamese_model.predict(sample_train)

for i in range(2000):
    sample = next(iter(train_dataset))
    print(i)
    print(sample[0].shape)

anchor_path = code_2_path(test_triplets.loc[0][0])
pos_path = code_2_path(test_triplets.loc[0][1])
neg_path = code_2_path(test_triplets.loc[0][2])
test = preprocess_triplets(anchor_path,pos_path,neg_path)


test2 = (test[0].numpy().reshape(224,224,3),
         test[1].numpy().reshape(224,224,3),
         test[2].numpy().reshape(224,224,3))

pred = siamese_model.predict(test)
#pred = siamese_model.predict(test_dataset,batch_size=32)


img = keras.preprocessing.image.load_img(
    code_2_path(test_triplets.loc[0][0]), target_size=(224,224))

img_array = (keras.preprocessing.image.img_to_array(img),
             keras.preprocessing.image.img_to_array(img),
             keras.preprocessing.image.img_to_array(img))
img_array = tf.expand_dims(img_array, 0)  # Create batch axis

predictions = siamese_model.predict(img_array)

sample = next(iter(train_dataset))

# serialize model to JSON
model_json = siamese_model.model_to_json()
with open(os.path.join(CURRENT_JOB_PATH,"final_model.json"), "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights(os.path.join(CURRENT_JOB_PATH,"final_model.h5"))
print("Saved model to disk")


siamese_network = create_siamese()
siamese_model = SiameseModel(siamese_network)
siamese_model.compile(optimizer=optimizers.Adam(0.0001))
siamese_model.load_weights(saved_model_path)

!zip -r /content/iml-hs21/task4/latest_job_05_22_08_54_05.zip  /content/iml-hs21/task4/jobs/job_05_22_08_54_05


!git reset HEAD jobs/*
!git status
!git log origin/main..HEAD
!git reset --soft HEAD~1
!git pull